# Generated by Django 4.0.3 on 2022-03-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_subscriptionpayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='vendor',
            new_name='provider_name',
        ),
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='vendor_transaction_id',
            new_name='provider_transaction_id',
        ),
        migrations.RenameField(
            model_name='subscriptionpaymentrefund',
            old_name='vendor',
            new_name='provider_name',
        ),
        migrations.RenameField(
            model_name='subscriptionpaymentrefund',
            old_name='vendor_transaction_id',
            new_name='provider_transaction_id',
        ),
    ]
