version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # specify the directory to scan for dependency files, e.g., "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0  # Only security updates will be opened as PRs
  - package-ecosystem: "docker"
    directory: "/"  # specify the directory to scan for dependency files, e.g., "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0  # Only security updates will be opened as PRs
