# Generated by Django 4.0.3 on 2022-05-31 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions_v0", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="subscriptions_v0.plan",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionpaymentrefund",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="subscriptions_v0.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="payments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
