# Generated by Django 4.0.3 on 2022-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_subscriptionpayment_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionpayment",
            name="subscription_charge_date",
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="subscription_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="subscription_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
