# Generated by Django 4.0.3 on 2022-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_remove_subscriptionpayment_subscription_charge_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plan",
            name="unique_plan_slug",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="slug",
        ),
    ]
