# Generated by Django 4.0.3 on 2022-06-06 11:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_remove_plan_unique_plan_slug_remove_plan_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(
                fields=["provider_codename", "provider_transaction_id"], name="subscriptio_provide_db7519_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpaymentrefund",
            index=models.Index(
                fields=["provider_codename", "provider_transaction_id"], name="subscriptio_provide_3a088f_idx"
            ),
        ),
    ]
