# Generated by Django 4.0.3 on 2022-06-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_v0", "0006_subscription_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="provider_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="provider_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
