# Generated by Django 4.0.3 on 2022-07-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_alter_subscriptionpayment_provider_transaction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
