# Generated by Django 4.0.3 on 2022-07-28 19:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0012_subscription_uid_subscriptionpayment_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
