# Generated by Django 4.0.3 on 2022-07-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_v0", "0016_remove_subscriptionpayment_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="subscription_uid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="subscriptions_v0.subscription",
                to_field="uid",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="original_payment_uid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="subscriptions_v0.subscriptionpayment",
                to_field="uid",
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="subscription_payment_uid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="subscriptions_v0.subscriptionpayment",
                to_field="uid",
            ),
        ),
    ]
