# Generated by Django 4.0.3 on 2022-07-28 19:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_alter_subscriptionpayment_subscription_uid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="id",
        ),
        migrations.RemoveField(
            model_name="subscriptionpayment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="subscriptionpaymentrefund",
            name="id",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="subscription_uid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="original_payment_uid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="subscriptions.subscriptionpayment",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tax",
            name="subscription_payment_uid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="subscriptions.subscriptionpayment",
            ),
        ),
    ]
