# Generated by Django 4.0.3 on 2022-07-28 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_v0", "0018_remove_subscription_id_remove_subscriptionpayment_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionpayment",
            old_name="subscription_uid",
            new_name="subscription",
        ),
        migrations.RenameField(
            model_name="subscriptionpaymentrefund",
            old_name="original_payment_uid",
            new_name="original_payment",
        ),
        migrations.RenameField(
            model_name="tax",
            old_name="subscription_payment_uid",
            new_name="subscription_payment",
        ),
    ]
