# Generated by Django 4.0.3 on 2022-07-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_v0", "0019_rename_subscription_uid_subscriptionpayment_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="original_payment",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to="subscriptions_v0.subscriptionpayment"
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="subscription_payment",
            field=models.ForeignKey(
                db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to="subscriptions_v0.subscriptionpayment"
            ),
        ),
    ]
