# Generated by Django 4.0.3 on 2022-07-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_v0", "0020_alter_subscriptionpaymentrefund_original_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="subscriptions_v0.subscription"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="original_payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="subscriptions_v0.subscriptionpayment"
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="subscription_payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="subscriptions_v0.subscriptionpayment"
            ),
        ),
    ]
