# Generated by Django 4.0.3 on 2022-08-01 11:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_v0", "0022_alter_subscriptionpayment_subscription_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"get_latest_by": "start"},
        ),
        migrations.AlterModelOptions(
            name="subscriptionpayment",
            options={"get_latest_by": "created"},
        ),
        migrations.AlterModelOptions(
            name="subscriptionpaymentrefund",
            options={"get_latest_by": "created"},
        ),
        migrations.AddField(
            model_name="plan",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
