# Generated by Django 4.1.3 on 2022-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0027_auto_20221109_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="level",
            field=models.SmallIntegerField(default=0),
        ),
    ]
