# Generated by Django 4.1.3 on 2022-12-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0029_alter_plan_charge_amount_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="is_negative",
            field=models.BooleanField(default=False),
        ),
    ]
