# Generated by Django 4.1.3 on 2023-07-06 11:34

from django.db import migrations

import subscriptions.v0.fields
import subscriptions.v0.models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions_v0", "0033_auto_20230706_1116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="initial_charge_offset",
            field=subscriptions.v0.fields.RelativeDurationField(
                blank=True,
                default=subscriptions.v0.models.default_initial_charge,
                encoder=subscriptions.v0.fields.RelativedeltaEncoder,
            ),
        ),
    ]
