# Generated by Django 4.0.2 on 2022-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='begin',
            field=models.DateTimeField(blank=True),
        ),
    ]
