# Generated by Django 4.0.2 on 2022-02-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_charge_amount_alter_usage_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='begin',
            new_name='start',
        ),
    ]
