# Generated by Django 4.0.2 on 2022-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_begin_subscription_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
