# Generated by Django 4.0.3 on 2022-03-09 20:42

from django.db import migrations
import subscriptions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='charge_period',
            field=subscriptions.fields.RelativeDurationField(blank=True, help_text='leave blank for one-time charge'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='subscription_duration',
            field=subscriptions.fields.RelativeDurationField(blank=True, help_text='DD HH:MM:SS; leave blank to make it an infinite subscription'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='burns_in',
            field=subscriptions.fields.RelativeDurationField(blank=True, help_text='leave blank to burn each recharge period'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='recharge_period',
            field=subscriptions.fields.RelativeDurationField(blank=True, help_text='leave blank for recharging only after each subscription prolongation (charge)'),
        ),
    ]
