# Generated by Django 4.0.3 on 2022-07-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20220711_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_prolong',
            field=models.BooleanField(default=True),
        ),
    ]
