# Generated by Django 4.0.3 on 2022-10-18 12:35

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpaymentrefund',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
    ]
