# Generated by Django 4.0.3 on 2022-10-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_alter_subscriptionpayment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=4096)),
                ('is_default', models.BooleanField(db_index=True)),
                ('features', models.ManyToManyField(to='subscriptions.feature')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Groups features connected to this plan together and allows sharing between plans of different duration.', null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.tier'),
        ),
    ]
