# Generated by Django 4.0.3 on 2022-10-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_feature_tier_plan_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Groups features connected to this plan together and allows sharing between plans of different duration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='subscriptions.tier'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
