# Generated by Django 4.1.3 on 2023-07-06 11:16

from django.db import migrations


def disable_default_plan_auto_prolong(apps, schema_editor):
    from subscriptions.functions import get_default_plan

    default_plan = get_default_plan()
    if not default_plan:
        return

    db_alias = schema_editor.connection.alias
    Subscription = apps.get_model("subscriptions", "Subscription")
    Subscription.objects.using(db_alias).filter(plan=default_plan.id, auto_prolong=True).update(auto_prolong=False)


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0032_subscription_initial_charge_offset_and_more"),
    ]

    operations = [
        migrations.RunPython(disable_default_plan_auto_prolong),
    ]
