# Generated by Django 4.1.3 on 2023-08-16 08:55

from django.db import migrations, models
import subscriptions.utils


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0036_auto_20230711_0614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=subscriptions.utils.AdvancedJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=subscriptions.utils.AdvancedJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Preauth"),
                    (2, "Completed"),
                    (3, "Cancelled"),
                    (4, "Error"),
                    (5, "Abandoned"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=subscriptions.utils.AdvancedJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpaymentrefund",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Preauth"),
                    (2, "Completed"),
                    (3, "Cancelled"),
                    (4, "Error"),
                    (5, "Abandoned"),
                ],
                default=0,
            ),
        ),
    ]
